### ISSUE TITLE
Timestamp values from database are stored as GMT -- not local time

### ISSUE THREAD

**Issue by kyle-danielson** [CPDTAC/CPViewInsights#4]
The timestamps in the graph are off by the number of hours away from GMT that the customer is in.

We need to either determine how to find out what timezone that the cpviewdb is taken from automatically or get user input (somehow).

**Comment by themadhatterz** [comment]
There is nothing in the database at this 'time' to detect timezone. All times are provided in GMT epoch. Will adjust graph labels to improve user experience until a more permanent solution is possible.

**Comment by themadhatterz** [comment]
#9 Addresses and will fix this.
